"""add coverage_ratio and exploration_score to environmentstate

Revision ID: 20251127_add_metrics
Revises: 20251123_add_obstacles_column
Create Date: 2025-11-27 02:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251127_add_metrics'
down_revision: Union[str, None] = '20251123_add_obstacles_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environmentstate', sa.Column('coverage_ratio', sa.Float(), nullable=True))
    op.add_column('environmentstate', sa.Column('exploration_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environmentstate', 'exploration_score')
    op.drop_column('environmentstate', 'coverage_ratio')
    # ### end Alembic commands ###
