"""add coverage_ratio and exploration_score to environmentstate

Revision ID: 20251127_add_metrics
Revises: 20251123_add_obstacles_column
Create Date: 2025-11-27 02:20:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20251127_add_metrics"
down_revision: str | None = "20251123_add_obstacles_column"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("environmentstate", sa.Column("coverage_ratio", sa.Float(), nullable=True))
  op.add_column("environmentstate", sa.Column("exploration_score", sa.Float(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("environmentstate", "exploration_score")
  op.drop_column("environmentstate", "coverage_ratio")
  # ### end Alembic commands ###
