"""add_num_robots_to_training_job

Revision ID: 466079de92c2
Revises: 99b7e499cd40
Create Date: 2025-12-01 00:09:27.426616

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "466079de92c2"
down_revision: str | Sequence[str] | None = "99b7e499cd40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "trainingjob", sa.Column("num_robots", sa.Integer(), nullable=False, server_default="1")
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("trainingjob", "num_robots")
  # ### end Alembic commands ###
