"""Add charging_stations

Revision ID: 5f8a29a7d9fe
Revises: 466079de92c2
Create Date: 2025-12-07 06:30:14.945484

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5f8a29a7d9fe'
down_revision: str | Sequence[str] | None = '466079de92c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environmentstate', sa.Column('charging_stations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environmentstate', 'charging_stations')
    # ### end Alembic commands ###
