"""add_robots_column_to_environment_state

Revision ID: 99b7e499cd40
Revises: 20251127_add_metrics
Create Date: 2025-12-01 00:07:21.206583

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99b7e499cd40"
down_revision: str | Sequence[str] | None = "20251127_add_metrics"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("environmentstate", sa.Column("robots", sa.JSON(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("environmentstate", "robots")
  # ### end Alembic commands ###
